name: sec_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  xml: ^5.4.1
  get: ^4.6.5
  dio: ^5.3.2
  intl: ^0.18.1
  location: ^5.0.3
#  geolocator: ^10.0.1
#  geocoding: ^2.1.0
  flutter_typeahead: ^4.7.0
#  flutter_google_places: ^0.3.0
  flutter_provider: ^2.1.0
  shared_preferences: ^2.2.1
  badges: ^3.1.2
  webview_flutter: ^4.2.4
  flutter_inappwebview: ^5.7.2+3
  google_sign_in: 6.1.5
  flutter_riverpod: ^2.4.0
  fpdart: ^1.1.0
  routemaster: ^1.0.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.5.0
  uuid: ^4.0.0
  any_link_preview: ^3.0.1
  sqflite: ^2.3.0
  http: ^1.1.0
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  path: ^1.8.3
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  like_button: ^2.0.5
  equatable: ^2.0.5
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  image_path: "images/logo.png"
  min_sdk_android: 21


dev_dependencies:
  flutter_test:
     sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
   - assets/logo.png
   - assets/intrologo.png
   - assets/smalllogo.png
   - assets/shopdata.json
   - assets/marker.png